"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class UserDataErrorEnum(google.protobuf.message.Message):
    """Proto file describing user data errors.

    Container for enum describing possible user data errors.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _UserDataError:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _UserDataErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UserDataError.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        UNSPECIFIED: UserDataErrorEnum.UserDataError.ValueType = ...  # 0
        """Enum unspecified."""

        UNKNOWN: UserDataErrorEnum.UserDataError.ValueType = ...  # 1
        """The received error code is not known in this version."""

        OPERATIONS_FOR_CUSTOMER_MATCH_NOT_ALLOWED: UserDataErrorEnum.UserDataError.ValueType = ...  # 2
        """Customer is not allowed to perform operations related to Customer Match."""

        TOO_MANY_USER_IDENTIFIERS: UserDataErrorEnum.UserDataError.ValueType = ...  # 3
        """Maximum number of user identifiers allowed for each mutate is 100."""

        USER_LIST_NOT_APPLICABLE: UserDataErrorEnum.UserDataError.ValueType = ...  # 4
        """Current user list is not applicable for the given customer."""

    class UserDataError(_UserDataError, metaclass=_UserDataErrorEnumTypeWrapper):
        """Enum describing possible request errors."""
        pass

    UNSPECIFIED: UserDataErrorEnum.UserDataError.ValueType = ...  # 0
    """Enum unspecified."""

    UNKNOWN: UserDataErrorEnum.UserDataError.ValueType = ...  # 1
    """The received error code is not known in this version."""

    OPERATIONS_FOR_CUSTOMER_MATCH_NOT_ALLOWED: UserDataErrorEnum.UserDataError.ValueType = ...  # 2
    """Customer is not allowed to perform operations related to Customer Match."""

    TOO_MANY_USER_IDENTIFIERS: UserDataErrorEnum.UserDataError.ValueType = ...  # 3
    """Maximum number of user identifiers allowed for each mutate is 100."""

    USER_LIST_NOT_APPLICABLE: UserDataErrorEnum.UserDataError.ValueType = ...  # 4
    """Current user list is not applicable for the given customer."""


    def __init__(self,
        ) -> None: ...
global___UserDataErrorEnum = UserDataErrorEnum
